# Generated by Django 4.1.3 on 2022-12-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_wishlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoria",
            old_name="usuario",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="despesa",
            old_name="usuario",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="renda",
            old_name="usuario",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="wishlist",
            old_name="usuario",
            new_name="user",
        ),
    ]
